name: scraper

on:
    workflow_dispatch:
    schedule:
        - cron: "0 12 * * *" # runs at 12:00 UTC everyday

jobs:
    generate_list:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v5

            - name: setup python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.x"

            - name: install Python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install tldextract aiohttp

            - name: Download URLs
              run: python scraper.py

            - name: create adblocking lists
              run: |
                  sed 's/^/\|\|/;s/$/\^/' urls.txt > urls_ABP.txt
                  sed 's/^/\|\|/;s/$/\^$all/' urls.txt > urls_UBO.txt

            - name: commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A
                  git diff --name-only --cached --exit-code || ( git commit -am "update lists" && git push )
